psql -d $dbname < generic_create_caresites.sql
psql -d $dbname < generic_create_conditions.sql
psql -d $dbname < generic_create_deaths.sql
psql -d $dbname < generic_create_locations.sql
psql -d $dbname < generic_create_measurements.sql
psql -d $dbname < generic_create_person.sql
psql -d $dbname < generic_create_procedures.sql
psql -d $dbname < generic_create_providers.sql
psql -d $dbname < generic_create_rx.sql
psql -d $dbname < generic_create_visits.sql
psql -d $dbname < qa_condition_load.sql
psql -d $dbname < qa_lab_load.sql
psql -d $dbname < qa_procedure_load.sql
psql -d $dbname < qa_rx_load.sql
psql -d $dbname < run_etl_load.sql
psql -d $dbname < run_locations.sql
psql -d $dbname < run_omop_load.sql
psql -d $dbname < run_qa.sql
